kotlin.code.style=official
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2G

## Forge Mod Information
modGroup=catx.feitu
modID=darknya
modName=DarkNya
modVersion=1.0.0
modDescription=Kawaii utility mod for blockgame.
modUrl=https://github.com/DarkMeowTeam/DarkMeowPremium
modUrlUpdate=https://github.com/DarkMeowTeam/DarkMeowPremium
modAuthors=NekoCurit,Miyaku
modLogoFile=assets/minecraft/darknya/big.png

forgeGradleVersion=6.+
minecraftVersion=1.12.2
forgeVersion=14.23.5.2860
mappingsChannel=stable
mappingsVersion=39-1.12

kotlinVersion=2.0.0
kotlinxCoroutineVersion=1.9.0-RC

kspVersion=2.0.0-1.0.22
fastRemapperVersion=1.0
jarOptimizerVersion=1.0
modLoaderVersion=1.0

viaversion_version=4.9.3
viabackwards_version=4.9.2
viarewind_version=3.0.6
vialoader_version=2.2.12
vialegacy_version=2.2.22-SNAPSHOT
viaaprilfools_version=2.0.11-SNAPSHOT
